version: '3'
services:
    vault:
        image: vault:1.0.3
        ports:
            - "8200:8200"
        networks:
            - somecompany-local
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: "dev-token"
          VAULT_ADDR: "http://127.0.0.1:8200"
        volumes:
            - .:/app
    db:
        image: postgres:11.2
        ports:
            - "5432:5432"
        networks:
            - somecompany-local
        environment:
            POSTGRES_PASSWORD: "PASSWORDO"
networks:
    nomad-local:
